import { readFileSync } from "node:fs"
import { join, dirname } from "node:path"
import { fileURLToPath } from "node:url"
import { describe, expect, test } from "vitest"
import mammoth from "mammoth"

/**
 * NOT a test of extractDocxText — that function's `{arrayBuffer}` call shape
 * is mammoth's *browser*-build API (which Vite resolves via the package's
 * `browser` field, confirmed by the production build succeeding). Under
 * plain Node/vitest, mammoth resolves to its Node build instead, which only
 * accepts `{path}`/`{buffer}` (confirmed by reading unzip.js) — so calling
 * extractDocxText's exact code here would test a different code path than
 * what ships, not the real one. This test instead proves the thing that
 * actually carries risk: that mammoth correctly parses THIS real generated
 * .docx file's structure and text, which is what feeds parseResumeText once
 * the browser-side extractDocxText hands it that same text at runtime.
 *
 * The .pdf/.docx fixtures are synthetic (fake name, generated by a script) —
 * see tools/guard-repo.mjs FIXTURE_ALLOWLIST, updated in the same commit.
 */

const FIXTURES_DIR = join(dirname(fileURLToPath(import.meta.url)), "__fixtures__")

test("mammoth correctly parses the real generated .docx fixture's text and structure", async () => {
  const buffer = readFileSync(join(FIXTURES_DIR, "sample_resume.docx"))
  const result = await mammoth.extractRawText({ buffer })
  expect(result.value).toContain("Alex Rivera")
  expect(result.value).toContain("alex.rivera@example.com")
  expect(result.value).toContain("EXPERIENCE")
  expect(result.value).toContain("Kestrel Energy Systems")
  expect(result.value).toContain("SKILLS")
})

describe("parseResumeText against mammoth's real output for this fixture", () => {
  test("the heuristic parser produces a correct draft from real mammoth output", async () => {
    const buffer = readFileSync(join(FIXTURES_DIR, "sample_resume.docx"))
    const result = await mammoth.extractRawText({ buffer })

    const { parseResumeText } = await import("./resume")
    const draft = parseResumeText(result.value)

    expect(draft.name).toBe("Alex Rivera")
    expect(draft.email).toBe("alex.rivera@example.com")
    expect(draft.experience.length).toBeGreaterThanOrEqual(2)
    expect(draft.experience[0].company).toBe("Nimbus Robotics")
    expect(draft.education.length).toBeGreaterThanOrEqual(2)
    expect(draft.skills).toContain("SQL")
  })
})
